substitutions:
  name: "atom-s3"
  friendly_name: "M5Stack Atom S3 bt proxy + cn105"
  clim_name: Clim Sejour

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: true
  project:
    name: esphome.clim_and_nt_proxy
    version: "24.7.4.1"

debug:
  update_interval: 5s

# Enable logging
logger:
  #hardware_uart: USB_CDC
  level: INFO

esp32:
  board: esp32-s3-devkitc-1

  #board: m5stack-cores3
  #variant: ESP32S3
  framework:
    type: arduino
    #type: esp-idf
    version: recommended
  flash_size: 8MB

# mqtt, api, ota, wifi, captive, web, time
<<: !include includes/ha-integration-config.yaml

# display button and api status binary_sensor configuration
<<: !include includes/binary-sensor-config.yaml

# displays infos on atom screen
<<: !include includes/display_config.yaml
# configure esp bluetooth proxy
<<: !include includes/bt-proxy-config.yaml

# cn105 mitsubishi climate config
<<: !include includes/climate-config.yaml
